<?php

namespace App\Filament\Resources;

use App\Filament\Resources\SuggestionResource\Pages;
use App\Filament\Resources\SuggestionResource\RelationManagers;
use App\Models\Suggestion;
use Filament\Actions\ViewAction;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class SuggestionResource extends Resource
{
    protected static ?string $model = Suggestion::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function getPluralLabel(): ?string
    {
        return __('dashboard/suggestions.suggestions'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return __('dashboard/suggestions.suggestion'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->label(__('dashboard/suggestions.name')),
                Tables\Columns\TextColumn::make('email')->label(__('dashboard/suggestions.email')),
                Tables\Columns\TextColumn::make('phone')->label(__('dashboard/suggestions.phone')),
                Tables\Columns\TextColumn::make('civil_id')->label(__('dashboard/suggestions.civil_id')),
                Tables\Columns\IconColumn::make('connected_to_service')
                    ->boolean()
                ->label(__('dashboard/suggestions.connected_to_service')),
                Tables\Columns\TextColumn::make('service_type')->label(__('dashboard/suggestions.service_type')),
                Tables\Columns\TextColumn::make('province.name')->label(__('dashboard/suggestions.province')),
                Tables\Columns\TextColumn::make('state.name')->label(__('dashboard/suggestions.state')),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSuggestions::route('/'),
            'create' => Pages\CreateSuggestion::route('/create'),
            'edit' => Pages\EditSuggestion::route('/{record}/edit'),
            'view' => Pages\ViewSuggestion::route('/{record}'),
        ];
    }
}
